// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlimtiwmeqlpggogyizn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsaW10aXdtZXFscGdnb2d5aXpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDAyODEsImV4cCI6MjA2MTAxNjI4MX0.OROhLKKpvG1SYv9oDDBf8xR6baNCI8v0PHDgrHgc--Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);